# Generated by Django 3.1.3 on 2024-05-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20240520_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='voters',
            new_name='voter',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='voters',
            new_name='voter',
        ),
    ]
